
services:
    fastapi_1:
        build: # use the dockerfile in the same dir
            context: .
            dockerfile: Dockerfile 
        image: fastapi_webserver:latest  # tells Docker Compose what to name (tag) the image after it’s built.
        ports: 
            - "2001:3003"  
    fastapi_2:
        build: # use the dockerfile in the same dir
            context: .
            dockerfile: Dockerfile 
        image: fastapi_webserver:latest  # tells Docker Compose what to name (tag) the image after it’s built.
        ports: 
            - "2002:3003"  
                
        