
services:
    fastapi_webserver:
        
        build: # use the dockerfile in the same dir
            context: .
            dockerfile: Dockerfile 
      image: fastapi_webserver:latest  # tells Docker Compose what to name (tag) the image after it’s built.
        deploy:
            replicas: 2
            restart_policy:
                condition: on-failure
                
        # this exposes port 2005 on the host and routes the traffic to port 3003 inside the containers
        ports:
            - published: 2222
              target: 3003
              protocol: tcp
            # mode: host = bypasses the routing mesh and binds the container port directly to the host’s network interface.
            # This leads to an error because each container tries to bind the host’s port 2222 directly.
            # Since you have a single node, only one container can successfully attach to that port.
            # The second container will fail to bind and repeatedly restart/crash.

networks:
    default:
        driver: overlay # for all swarm "overlay" network is recommended (mandatory if multiple node setup)
        attachable: true   # <-- important! Docker allows containers (and the Compose process) to attach to the overlay network, preventing the PermissionDenied error. 