
services:

    registry:  # local docker registry to handle and store the images
        image: registry:2
        volumes:
        - registry-data:/var/lib/registry
        ports: 
        - "5000:5000" # For internal service-to-service communication on the overlay network, this isn’t required. 
        # But to manually push and pull images, you need to expose the port to the host.
        networks:
          swarm-net:
            aliases:
              - registry

volumes:  # this creates a persistend docker volume
  registry-data:

networks:
    swarm-net:
        # external: true   # if you wnat to connect to an existing network
        name: swarm-net  # with this the name of the network is setted
        driver: overlay # for all swarm "overlay" network is recommended (mandatory if multiple node setup)
        attachable: true   # <-- important! Docker allows containers (and the Compose process) to attach to the overlay network, preventing the PermissionDenied error. 
